### ISSUE TITLE
DockerPi 4 Channel Relay on Homeassistant OS

### ISSUE THREAD

**Issue by HAPO64** [geeekpi/dockerpi#7]
Hi community,
I bought a DockerPi 4 Channel Relay HAT for my installation runnung HA OS maybe by mistake. 
Its operation is not based on GPIO pins but on I2C. Both are not supported on HA OS core since 2022. 
There is support on HACS for GPIO HAT's but I found no support for I2C.
Maybe somebody have experiance and can help?!
regards Josef

**Comment by yoyojacky** [comment]
Hi, Josef, 
I think it is hard to use this board on a docker environment, This board has an MCU on board, and it will communicate with Raspberry Pi via  I2C protocol, I have no idea on how to configure HAOS to enable I2C port and how to control the I2C port via docker image. so that we recommend you change it to Raspberry Pi OS. it may easier for controlling this board.
